[workspace]
members = ["programs/fair_token"]

[workspace.dependencies]
anchor-lang = "0.31.1"
anchor-spl  = "0.31.1"

[profile.release]
opt-level = "s"
codegen-units = 1
overflow-checks = true
lto = "fat"        # optional but common for Solana
